title: Walden
# subtitle: ""  # 首頁副標題，填入內容即可開啟
description: 張文柏的個人網站
image: /assets/images/walden_card.png
url: "https://walden-wpc.github.io"

# Build settings
# NO theme: minima — we use our own _layouts/
future: true
timezone: Asia/Taipei
kramdown:
  hard_wrap: true

plugins:
  - jekyll-feed

# Social Links
social:
  linkedin: https://www.linkedin.com/in/wen-po-chang-842554292/
  # mastodon: https://mastodon.social/@yourname
  email: wpc.walden@gmail.com

goatcounter: walden